// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eynek-account/Current.tsx": () => import("../components/mockups/eynek-account/Current.tsx"),
  "./components/mockups/eynek-account/Modern.tsx": () => import("../components/mockups/eynek-account/Modern.tsx")
};
